version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taskflow-db
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - taskflow-net

  backend:
    build:
      context: ./backend
    container_name: taskflow-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskflow
      SPRING_DATASOURCE_USERNAME: taskflow
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - taskflow-net
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "--", "java", "-jar", "app.jar"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskflow-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - taskflow-net
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:

networks:
  taskflow-net:
